# Generated by Django 3.0.3 on 2020-02-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('POL', 'Politics'), ('ENVIRONMENT', 'Environment'), ('TECH', 'Tech'), ('FINANCE', 'Finance')], default='POL', max_length=20),
        ),
    ]
